name: Unit Tests
env:
  # increment this when downloads substantially change to avoid the internet
  DOWNLOAD_CACHE_VERSION: '9'
  CAPTURE_PROCESS_REPLAY: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master
      - objdump_path
  pull_request:
  workflow_dispatch:

jobs:
# ****** OSX Tests ******

  testmetal2:
    name: MacOS (unit)
    runs-on: macos-14
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Environment
      uses: ./.github/actions/setup-tinygrad
      with:
        key: metal2
        deps: testing
        python-version: '3.11'
        amd: 'true'
        cuda: 'true'
        llvm: 'true'
    - name: test disas
      run: |
        which llvm-objdump
        PYTHONPATH=. MOCKGPU=1 AMD=1 DEBUG=8 python test/test_ops.py TestOps.test_add
